version: 2

project_name: gotls

builds:
  - id: gotls
    binary: gotls
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X 'github.com/rodneyxr/gotls/cmd.version={{.Version}}' -X 'github.com/rodneyxr/gotls/cmd.commit={{.ShortCommit}}' -X 'github.com/rodneyxr/gotls/cmd.date={{.Date}}'"
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: gotls
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: rodneyxr
    name: gotls
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto
